services:
  - type: web
    name: aifsd-mse2-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20
      - key: FRONTEND_URL
        sync: false
      - key: FRONTEND_URL_2
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false

  - type: static
    name: aifsd-mse2-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: REACT_APP_API_URL
        sync: false
